default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
        fail_fast: true
      - id: end-of-file-fixer
        stages: [commit]
        fail_fast: true
      - id: check-added-large-files
        stages: [commit]
        fail_fast: true
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
        name: isort (python)
        fail_fast: true
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.2 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        stages: [commit]
        args: [--config=pyproject.toml]
        fail_fast: true
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--max-line-length=200]
        stages: [commit]
        fail_fast: true
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
        args: [--max-line-length=200, --diff]
        stages: [commit]
        fail_fast: true
  - repo: local
    hooks:
      - id: test
        stages: [commit]
        name: test
        language: system
        entry: pdm run test
        types: [python]
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: coverage
        stages: [push]
        name: coverage
        language: system
        entry: pdm run coverage
        types: [python]
        always_run: true
        pass_filenames: false
