version: "3.5"
services:
  # Postgres
  postgres:
    restart: always
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ddd
    volumes:
      - "postgres-data-ddd:/var/lib/postgresql/data"
    networks:
      - postgres_ddd
  # Api server
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ddd
    depends_on:
      - postgres
    networks:
      - postgres_ddd
    volumes:
      - ./src:/projects/src
    command: ["pdm", "run", "start_dev"]

volumes:
  postgres-data-ddd:
networks:
  postgres_ddd:
    driver: bridge
